FORMAT: 1A
HOST: https://cms.api.brightcove.com/v1beta1

# CMS API
The CMS API allows creation of video objects and retrieval of video information.

## Base URL

The base URL for these APIs is:

    https://cms.api.brightcove.com/v1beta1

# Group Manipulate Video Information

Create a single video and retrieve various video information. The endpoint is determined by the information requested. Some retrieval requests can use either the video ID or reference ID.

## POST to create a video object/GET information on all videos [/accounts/{accountId}/videos]

### POST
Supply a name and create a video object with that name. The response will contain the ID for the video object.

+ Parameters

    + accountId (required string `20318290001`) ... The Video Cloud account id (in older versions of Studio called the Publisher ID)

+ Request

    + Headers

            Authorization: Bearer {token}
            Content-Type: application/json

    + Body

            {
                "name": "My New Video"
            }

+ Response 200

    + Body

            {
                "id": "1234",
                "name": "My New Video"
            }
            
+ Response 400

    + Body

            {}

### GET
Use only the account ID and retrieve information on all videos in the account.

+ Parameters

    + accountId (required string `20318290001`) ... The Video Cloud account id (in older versions of Studio called the Publisher ID)

+ Request

    + Headers

            Authorization: Bearer {token}
            Content-Type: application/json

    + Body

            {}

+ Response 200

    + Body

            [ {
              "id" : "3790053031001",
              "account_id" : "20318290001",
              "complete" : true,
              "created_at" : "2014-09-17T15:56:59.564Z",
              "cue_points" : [ ],
              "custom_fields" : {
                "topic" : "Gallery - Customizing a Site",
                "inproduct" : "Gallery"
              },...]
            
+ Response 400

    + Body

            [ {
              "error_code" : "NOT_FOUND",
              "message" : "Resource does not exist."
            } ]

## GET a single video [/accounts/{accountId}/videos/{videoId}]

### GET
Use the video ID to retrieve information for a single video

+ Parameters

    + accountId (required string `20318290001`) ... The Video Cloud account id (in older versions of Studio called the Publisher ID)
    + videoId (required string `12345678`) ... The ID of the video

+ Request

    + Headers

            Authorization: Bearer {token}
            Content-Type: application/json

    + Body

            {}

+ Response 200

    + Body

            {
              "id" : "610747847001",
              "account_id" : "20318290001",
              "complete" : true,
              "created_at" : "2010-09-17T21:35:49.385Z",
              "cue_points" : [ ],
              "custom_fields" : {
                "inproduct" : "Video Cloud",
                "topic" : "VC - General Information"
              },
              "description" : "Learn about Brightcove's Smart players that          will allow your videos to be viewed on desktop and mobile devices",
              "duration" : 136627,
              "geo" : null,
              "long_description" : null,
              "name" : "HTML5 Smart Players",
              "reference_id" : "610747847001",
              "schedule" : null,
              "sharing" : {
                "by_external_acct" : true,
                "by_id" : "301925175",
                "source_id" : "407591857001",
                "to_external_acct" : false,
                "by_reference" : false
              },
              "state" : "INACTIVE",
              "tags" : [ "basics", "studio", "3play_processed", "players", "drupal", "express paid" ],
              "updated_at" : "2013-12-12T14:44:26.517Z"
            }
            
+ Response 400

    + Body

            [ {
              "error_code" : "NOT_FOUND",
              "message" : "Resource does not exist."
            } ]

## GET a single video by reference ID [/accounts/{accountId}/videos/ref:{refId}]

### GET
Use the video reference ID to retrieve information for a single video

+ Parameters

    + accountId (required string `20318290001`) ... The Video Cloud account id (in older versions of Studio called the Publisher ID)
    + refId (required string `12345678`) ... The reference ID of the video

+ Request

    + Headers

            Authorization: Bearer {token}
            Content-Type: application/json

    + Body

            {}

+ Response 200

    + Body

            {
              "id" : "610747847001",
              "account_id" : "20318290001",
              "complete" : true,
              "created_at" : "2010-09-17T21:35:49.385Z",
              "cue_points" : [ ],
              "custom_fields" : {
                "inproduct" : "Video Cloud",
                "topic" : "VC - General Information"
              },
              "description" : "Learn about Brightcove's Smart players that          will allow your videos to be viewed on desktop and mobile devices",
              "duration" : 136627,
              "geo" : null,
              "long_description" : null,
              "name" : "HTML5 Smart Players",
              "reference_id" : "610747847001",
              "schedule" : null,
              "sharing" : {
                "by_external_acct" : true,
                "by_id" : "301925175",
                "source_id" : "407591857001",
                "to_external_acct" : false,
                "by_reference" : false
              },
              "state" : "INACTIVE",
              "tags" : [ "basics", "studio", "3play_processed", "players", "drupal", "express paid" ],
              "updated_at" : "2013-12-12T14:44:26.517Z"
            }
            
+ Response 400

    + Body

            [ {
              "error_code" : "NOT_FOUND",
              "message" : "Resource does not exist."
            } ]

## GET the images for a specific video by video ID [/accounts/{accountId}/videos/{videoId}/images]

### GET
Retrieve video's images by video ID

+ Parameters

    + accountId (required string `20318290001`) ... The Video Cloud account id (in older versions of Studio called the Publisher ID)
    + videoId (required string `12345678`) ... The ID of the video

+ Request

    + Headers

            Authorization: Bearer {token}
            Content-Type: application/json

    + Body

            {}

+ Response 200

    + Body

            {
              "thumbnail" : {
                "id" : "2900507794001",
                "src" : "http://brightcove04.o.brightcove.com/20318290001/20318290001_2900507794001_th-52a1fae0e4b00f8cb61e1f72-1592194025001.jpg?pubId=20318290001"
              },
              "poster" : {
                "id" : "2900507792001",
                "src" : "http://brightcove04.o.brightcove.com/20318290001/20318290001_2900507792001_vs-52a1fae0e4b00f8cb61e1f72-1592194025001.jpg?pubId=20318290001"
              }
            }
            
+ Response 400

    + Body

            [ {
              "error_code" : "NOT_FOUND",
              "message" : "Resource does not exist."
            } ]

## GET the images for a specific video  by reference ID [/accounts/{accountId}/videos/ref:{refId}/images]

### GET
Retrieve video's images by reference ID

+ Parameters

    + accountId (required string `20318290001`) ... The Video Cloud account id (in older versions of Studio called the Publisher ID)
    + refId (required string `12345678`) ... The reference ID of the video

+ Request

    + Headers

            Authorization: Bearer {token}
            Content-Type: application/json

    + Body

            {}

+ Response 200

    + Body

            {
              "thumbnail" : {
                "id" : "2900507794001",
                "src" : "http://brightcove04.o.brightcove.com/20318290001/20318290001_2900507794001_th-52a1fae0e4b00f8cb61e1f72-1592194025001.jpg?pubId=20318290001"
              },
              "poster" : {
                "id" : "2900507792001",
                "src" : "http://brightcove04.o.brightcove.com/20318290001/20318290001_2900507792001_vs-52a1fae0e4b00f8cb61e1f72-1592194025001.jpg?pubId=20318290001"
              }
            }
            
+ Response 400

    + Body

            [ {
              "error_code" : "NOT_FOUND",
              "message" : "Resource does not exist."
            } ]

## GET the sources for a specific video  by ID [/accounts/{accountId}/videos/{videoId}/sources]

### GET
Retrieve video's sources by video ID

+ Parameters

    + accountId (required string `20318290001`) ... The Video Cloud account id (in older versions of Studio called the Publisher ID)
    + videoId (required string `12345678`) ... The ID of the video

+ Request

    + Headers

            Authorization: Bearer {token}
            Content-Type: application/json

    + Body

            {}

+ Response 200

    + Body

            [ {
              "id" : "2900506580001",
              "app_name" : "rtmp://cp150446.edgefcs.net/ondemand",
              "stream_name" : "mp4:20318290001/20318290001_2900506580001_video-player-module-demo.mp4?__nn__=1497926354001&slist=20318290001/&auth=daEbUb_a_a.b_a2bQd0cpcrdXa9a2c7bXdl-buleeG-bWG-qmAAuptx_yEyo_CEAA_GvB&aifp=bcosuds",
              "codec" : "H264",
              "container" : "MP4",
              "encoding_rate" : 1063687,
              "duration" : 700639,
              "height" : 720,
              "width" : 1280,
              "size" : 90933140,
              "uploaded_at" : "2013-12-06T16:38:13.683Z"
            }, {
              "id" : "2900506580001",
              "src" : "http://uds.ak.o.brightcove.com/20318290001/20318290001_2900506580001_video-player-module-demo.mp4",
              "codec" : "H264",
              "container" : "MP4",
              "encoding_rate" : 1063687,
              "duration" : 700639,
              "height" : 720,
              "width" : 1280,
              "size" : 90933140,
              "uploaded_at" : "2013-12-06T16:38:13.683Z"
            }, {
              "id" : "2900507785001",
              "app_name" : "rtmp://cp150446.edgefcs.net/ondemand",
              "stream_name" : "mp4:20318290001/20318290001_2900507785001_video-player-module-demo.mp4?__nn__=1497926354001&slist=20318290001/&auth=daEbUb_a_a.b_a2bQd0cpcrdXa9a2c7bXdl-buleeG-bWG-qmAAuptx_yEyo_CEAA_GvB&aifp=bcosuds",
              "codec" : "H264",
              "container" : "MP4",
              "encoding_rate" : 676687,
              "duration" : 700639,
              "height" : 720,
              "width" : 1280,
              "size" : 59849740,
              "uploaded_at" : "2013-12-06T16:37:35.397Z"
            }, {
              "id" : "2900507785001",
              "src" : "http://uds.ak.o.brightcove.com/20318290001/20318290001_2900507785001_video-player-module-demo.mp4",
              "codec" : "H264",
              "container" : "MP4",
              "encoding_rate" : 676687,
              "duration" : 700639,
              "height" : 720,
              "width" : 1280,
              "size" : 59849740,
              "uploaded_at" : "2013-12-06T16:37:35.397Z"
            }, {
              "src" : "http://c.brightcove.com/services/mobile/streaming/index/master.m3u8?videoId=2900459533001&pubId=20318290001",
              "container" : "M2TS",
              "codec" : "H264"
            } ]
            
+ Response 400

    + Body

            [ {
              "error_code" : "NOT_FOUND",
              "message" : "Resource does not exist."
            } ]

## GET the sources for a specific video  by reference ID [/accounts/{accountId}/videos/ref:{refId}/sources]

### GET
Retrieve video's sources by reference ID

+ Parameters

    + accountId (required string `20318290001`) ... The Video Cloud account id (in older versions of Studio called the Publisher ID)
    + refId (required string `12345678`) ... The reference ID of the video

+ Request

    + Headers

            Authorization: Bearer {token}
            Content-Type: application/json

    + Body

            {}

+ Response 200

    + Body

            [ {
              "id" : "2900506580001",
              "app_name" : "rtmp://cp150446.edgefcs.net/ondemand",
              "stream_name" : "mp4:20318290001/20318290001_2900506580001_video-player-module-demo.mp4?__nn__=1497926354001&slist=20318290001/&auth=daEbUb_a_a.b_a2bQd0cpcrdXa9a2c7bXdl-buleeG-bWG-qmAAuptx_yEyo_CEAA_GvB&aifp=bcosuds",
              "codec" : "H264",
              "container" : "MP4",
              "encoding_rate" : 1063687,
              "duration" : 700639,
              "height" : 720,
              "width" : 1280,
              "size" : 90933140,
              "uploaded_at" : "2013-12-06T16:38:13.683Z"
            }, {
              "id" : "2900506580001",
              "src" : "http://uds.ak.o.brightcove.com/20318290001/20318290001_2900506580001_video-player-module-demo.mp4",
              "codec" : "H264",
              "container" : "MP4",
              "encoding_rate" : 1063687,
              "duration" : 700639,
              "height" : 720,
              "width" : 1280,
              "size" : 90933140,
              "uploaded_at" : "2013-12-06T16:38:13.683Z"
            }, {
              "id" : "2900507785001",
              "app_name" : "rtmp://cp150446.edgefcs.net/ondemand",
              "stream_name" : "mp4:20318290001/20318290001_2900507785001_video-player-module-demo.mp4?__nn__=1497926354001&slist=20318290001/&auth=daEbUb_a_a.b_a2bQd0cpcrdXa9a2c7bXdl-buleeG-bWG-qmAAuptx_yEyo_CEAA_GvB&aifp=bcosuds",
              "codec" : "H264",
              "container" : "MP4",
              "encoding_rate" : 676687,
              "duration" : 700639,
              "height" : 720,
              "width" : 1280,
              "size" : 59849740,
              "uploaded_at" : "2013-12-06T16:37:35.397Z"
            }, {
              "id" : "2900507785001",
              "src" : "http://uds.ak.o.brightcove.com/20318290001/20318290001_2900507785001_video-player-module-demo.mp4",
              "codec" : "H264",
              "container" : "MP4",
              "encoding_rate" : 676687,
              "duration" : 700639,
              "height" : 720,
              "width" : 1280,
              "size" : 59849740,
              "uploaded_at" : "2013-12-06T16:37:35.397Z"
            }, {
              "src" : "http://c.brightcove.com/services/mobile/streaming/index/master.m3u8?videoId=2900459533001&pubId=20318290001",
              "container" : "M2TS",
              "codec" : "H264"
            } ]
            
+ Response 400

    + Body

            [ {
              "error_code" : "NOT_FOUND",
              "message" : "Resource does not exist."
            } ]